# Generated by Django 4.2.1 on 2023-07-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
