# Generated by Django 4.2.1 on 2023-07-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Login'},
        ),
    ]
